from .elements import create_fire, create_water

__version__ = "1.0.0"
__author__ = "Master Pythonicus"

# This tells Flake8 these imports are intentionally exposed
__all__ = [
    "create_fire",
    "create_water"
]

"""
The __pycache__ directory is automatically generated by Python
when a module is imported.
It stores compiled bytecode versions (.pyc files) of your Python scripts.
Similar to object files (.o) in C, this compiled bytecode allows Python
to load and execute the imported modules much faster on subsequent runs.
These files are safely managed by Python for performance optimization and
should always be excluded from version control by adding '__pycache__/'
to your .gitignore file.
"""
